<?xml version="1.0"?>
<definitions name="StockQuote"

             targetNamespace="http://example.com/locatorTest.wsdl"
             xmlns:tns="http://example.com/locatorTest.wsdl"
             xmlns:xsd1="http://example.com/stockquote.xsd"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:mock="urn:mock"
             xmlns:ext="http://example.com/stockquote.wsdl"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

    <import namespace="http://example.com/stockquote.wsdl" location="extensionTest.wsdl"/>

    <binding name="TestSOAPBinding" type="ext:StockQuotePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetLastTradePrice">
            <soap:operation soapAction="http://example.com/GetLastTradePrice"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <mock:mockExtensibilityElement/>
    </binding>

    <service name="TestImportService">
        <port name="TestImportPort" binding="tns:TestSOAPBinding">
            <soap:address location="http://example.com/stockquote"/>
        </port>
    </service>

</definitions>